//
//  File.swift
//  
//
//  Created by Leif Ibsen on 10/03/2024.
//

import Foundation
@testable import SwiftDilithium

struct Util {
    
    static func hex2bytes(_ x: String) -> Bytes {
        let b = [Byte](x.utf8)
        var bytes = Bytes(repeating: 0, count: b.count / 2)
        for i in 0 ..< bytes.count {
            let b0 = b[2 * i]
            let b1 = b[2 * i + 1]
            bytes[i] = ((b0 > 57 ? b0 - 97 + 10 : b0 - 48) << 4) | (b1 > 57 ? b1 - 97 + 10 : b1 - 48)
        }
        return bytes
    }
    
    static func bytes2hex(_ x: Bytes) -> String {
        let hexDigits = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "a", "b", "c", "d", "e", "f"]
        var s = ""
        for b in x {
            s.append(hexDigits[Int(b >> 4)])
            s.append(hexDigits[Int(b & 0xf)])
        }
        return s
    }
    
    struct katTest {
        // Key generation seed
        let seed: Bytes
        // Public key SHA2-256 digest
        let pkDigest: Bytes
        // Secret key SHA2-256 digest
        let skDigest: Bytes
    }
    
    // KAT data generated by a CRYSTALS-Dilithium Python Implementation
    // modified slightly to adjust it to the NIST FIPS 204 draft
    static func makeKatTests(_ katTests: inout [katTest], _ data: Data) {
        let s = String(decoding: data, as: UTF8.self)
        var lines = s.components(separatedBy: .newlines)
        let groups = lines.count / 5
        for i in 0 ..< groups {
            let j = i * 5
            lines[j + 1].removeFirst(7)
            lines[j + 2].removeFirst(11)
            lines[j + 3].removeFirst(11)
        }
        for i in 0 ..< groups {
            let j = i * 5
            let seed = hex2bytes(lines[j + 1])
            let pkDigest = hex2bytes(lines[j + 2])
            let skDigest = hex2bytes(lines[j + 3])
            katTests.append(katTest(seed: seed, pkDigest: pkDigest, skDigest: skDigest))
        }
    }

}
